apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  gitea.uds.ura.go.ug: |
    -----BEGIN CERTIFICATE-----
    MIIB3DCCAYKgAwIBAgIQdEvXAqxqc4ezcn10O3xsOzAKBggqhkjOPQQDAjBNMQsw
    CQYDVQQGEwJUUjERMA8GA1UEChMIRGF0YW1pbmQxEDAOBgNVBAsTB0RhdGFPcHMx
    GTAXBgNVBAMTEERhdGFtaW5kIFJvb3QgQ0EwIBcNMjUwOTE4MTE0MTExWhgPMjEy
    NTA4MjUxMTQxMTFaME0xCzAJBgNVBAYTAlRSMREwDwYDVQQKEwhEYXRhbWluZDEQ
    MA4GA1UECxMHRGF0YU9wczEZMBcGA1UEAxMQRGF0YW1pbmQgUm9vdCBDQTBZMBMG
    ByqGSM49AgEGCCqGSM49AwEHA0IABEXeknSYMgH1pfzT+YQJSD5eFWd9uznar2DN
    0lGG6VYdkx/fJ1H7c++q4+qVJN5lqV5L3tIDqICANT0KdjgCZUmjQjBAMA4GA1Ud
    DwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS+7Xne3oceKDc6
    lYCe8SgjU4k43zAKBggqhkjOPQQDAgNIADBFAiEA9sfUEXxemrbOspDYByjTz6gM
    5Y2NB5raYJxfHLGa8A8CIDOTWs5qh45cDMbGcvfzkk6jkc90hx+y8gLksOwTSWkX
    -----END CERTIFICATE-----
