apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-pipelines--backend-object-store-auth
  namespace: kubeflow
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "4G6AKKM8YQHK8INFGNICOJRVRBPB8BLKZCT3YLMAL0PXMVZDMWHFMMZV1TC7GXZ40OINP3ULKU8M1Y77PBXJD67HIIO376SUJKN51EVC1"
  AWS_SECRET_ACCESS_KEY: "HWQMOF0Y1BQIAS4GNFGUWSI9N0V2UYXSCFO591IMHMOAH16JVZ1NJQPDKIIZ9S2WH8WV58IIUXVAFJROX3XCVYHWQMX5ZU7BFA"

---

apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-pipelines--profile-object-store-auth--team-1
  namespace: kubeflow
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "TBX5OIZUHEXK6X1IBBC7DP6CS779065VTDYD"
  AWS_SECRET_ACCESS_KEY: "PZ7HJOW0TEQHVXC1BBC06OX3Q66FTJJ89"

---

apiVersion: v1
kind: Secret
metadata:
  name: cloned--kubeflow-pipelines--backend-object-store-auth
  namespace: kubeflow
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "4G6AKKM8YQHK8INFGNICOJRVRBPB8BLKZCT3YLMAL0PXMVZDMWHFMMZV1TC7GXZ40OINP3ULKU8M1Y77PBXJD67HIIO376SUJKN51EVC1"
  AWS_SECRET_ACCESS_KEY: "HWQMOF0Y1BQIAS4GNFGUWSI9N0V2UYXSCFO591IMHMOAH16JVZ1NJQPDKIIZ9S2WH8WV58IIUXVAFJROX3XCVYHWQMX5ZU7BFA"
  
---

apiVersion: v1
kind: Secret
metadata:
  name: cloned--pipelines-object-store-auth
  namespace: team-1-prod
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "TBX5OIZUHEXK6X1IBBC7DP6CS779065VTDYD"
  AWS_SECRET_ACCESS_KEY: "PZ7HJOW0TEQHVXC1BBC06OX3Q66FTJJ89"