apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  env:
    - name: HTTPS_PROXY
      value: http://proxy.ura.local:8080
    - name: NO_PROXY
      value: 127.0.0.1,localhost,.svc,.cluster.local
